#!/bin/bash -l

set -e

# pwd here is /github/workspace
# We're expecting the json files generated by the Changes Action to be in the ~ home directory

if [ ! -f ~/services.json ]; then
  echo "Services File does not exist."
  echo "Please install the changes action at https://github.com/Knotel/actions/changes"
  echo "You will need to install dependencies before running this action."
  exit 1
else
  node /action/lib/run.js
fi


